sdk:
  - stable
  - dev

stages:
  - analyze_and_format:
      - group:
          - format
          - analyze: --fatal-infos .
  - unit_test:
      - test:
      - command: dart run build_runner test --delete-conflicting-outputs -- -p chrome
      - command: dart run build_runner test --release --delete-conflicting-outputs -- -p chrome
  - unit_test_native:
      - test:
        os:
          - macos
          - windows
      - command: dart run build_runner test --delete-conflicting-outputs -- -p firefox
      - command: dart run build_runner test --release --delete-conflicting-outputs -- -p firefox
