name: amplify_push_notifications_pinpoint_ios_example
description: Demonstrates how to use the amplify_push_notifications_pinpoint_ios plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  amplify_push_notifications_pinpoint:
    path: ../../amplify_push_notifications_pinpoint
  amplify_flutter:
    path: ../../../../amplify/amplify_flutter
  cupertino_icons: ^1.0.2

dependency_overrides:
  amplify_push_notifications_pinpoint_ios:
    path: ../
  amplify_flutter_ios:
    path: ../../../../amplify/amplify_flutter_ios

dev_dependencies:
  flutter_test:
    sdk: flutter
  amplify_lints: ^1.0.0

flutter:
  uses-material-design: true
