name: non_auth_pentest
description: For testing amplify.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  # amplify_analytics_pinpoint:
  #   path: ../packages/analytics/amplify_analytics_pinpoint
  amplify_api:
    path: ../packages/api/amplify_api
  amplify_auth_cognito:
    path: ../packages/auth/amplify_auth_cognito
  amplify_flutter:
    path: ../packages/amplify/amplify_flutter
  amplify_authenticator:
    path: ../packages/amplify_authenticator
  amplify_storage_s3:
    path: ../packages/storage/amplify_storage_s3
  file_picker: ^5.2.0+1
  flutter_json_viewer: ^1.0.1
  go_router: ^5.0.5
  aws_common: ^0.2.0
  sqlite3_flutter_libs: ^0.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

dependency_overrides: 
  # amplify_analytics_pinpoint:
  #   path: ../packages/analytics/amplify_analytics_pinpoint
  # amplify_analytics_pinpoint_android:
  #   path: ../packages/analytics/amplify_analytics_pinpoint_android
  # amplify_analytics_pinpoint_ios:
  #   path: ../packages/analytics/amplify_analytics_pinpoint_ios
  amplify_api:
    path: ../packages/api/amplify_api
  amplify_api_android:
    path: ../packages/api/amplify_api_android
  amplify_api_ios:
    path: ../packages/api/amplify_api_ios
  amplify_auth_cognito:
    path: ../packages/auth/amplify_auth_cognito
  amplify_auth_cognito_android:
    path: ../packages/auth/amplify_auth_cognito_android
  amplify_auth_cognito_dart:
    path: ../packages/auth/amplify_auth_cognito_dart
  amplify_auth_cognito_ios:
    path: ../packages/auth/amplify_auth_cognito_ios
  amplify_authenticator:
    path: ../packages/amplify_authenticator
  amplify_core:
    path: ../packages/amplify_core
  amplify_datastore_plugin_interface:
    path: ../packages/amplify_datastore_plugin_interface
  amplify_flutter:
    path: ../packages/amplify/amplify_flutter
  amplify_flutter_android:
    path: ../packages/amplify/amplify_flutter_android
  amplify_flutter_ios:
    path: ../packages/amplify/amplify_flutter_ios
  amplify_lints:
    path: ../packages/amplify_lints
  amplify_secure_storage:
    path: ../packages/secure_storage/amplify_secure_storage
  amplify_secure_storage_dart:
    path: ../packages/secure_storage/amplify_secure_storage_dart
  amplify_storage_s3:
    path: ../packages/storage/amplify_storage_s3
  amplify_storage_s3_dart:
    path: ../packages/storage/amplify_storage_s3_dart
  amplify_test:
    path: ../packages/amplify_test
  aws_common:
    path: ../packages/aws_common
  aws_signature_v4:
    path: ../packages/aws_signature_v4
  smithy:
    path: ../packages/smithy/smithy
  smithy_aws:
    path: ../packages/smithy/smithy_aws
  worker_bee:
    path: ../packages/worker_bee/worker_bee
