name: pentest_soundboard
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  amplify_auth_cognito:
    path: ../packages/auth/amplify_auth_cognito
  amplify_authenticator:
    path: ../packages/amplify_authenticator
  amplify_flutter:
    path: ../packages/amplify/amplify_flutter
  async: ^2.8.2
  collection: ^1.15.0
  flutter:
    sdk: flutter

dependency_overrides:
  amplify_api:
    path: ../packages/api/amplify_api
  amplify_api_android:
    path: ../packages/api/amplify_api_android
  amplify_api_ios:
    path: ../packages/api/amplify_api_ios
  amplify_authenticator:
    path: ../packages/amplify_authenticator
  amplify_auth_cognito:
    path: ../packages/auth/amplify_auth_cognito
  amplify_auth_cognito_android:
    path: ../packages/auth/amplify_auth_cognito_android
  amplify_auth_cognito_dart:
    path: ../packages/auth/amplify_auth_cognito_dart
  amplify_auth_cognito_ios:
    path: ../packages/auth/amplify_auth_cognito_ios
  amplify_core:
    path: ../packages/amplify_core
  amplify_flutter:
    path: ../packages/amplify/amplify_flutter
  amplify_flutter_ios:
    path: ../packages/amplify/amplify_flutter_ios
  amplify_flutter_android:
    path: ../packages/amplify/amplify_flutter_android
  amplify_secure_storage:
    path: ../packages/secure_storage/amplify_secure_storage
  amplify_secure_storage_dart:
    path: ../packages/secure_storage/amplify_secure_storage_dart
  aws_common:
    path: ../packages/aws_common
  aws_signature_v4:
    path: ../packages/aws_signature_v4
  worker_bee:
    path: ../packages/worker_bee/worker_bee

dev_dependencies:
  amplify_lints:
    path: ../packages/amplify_lints
  analysis_server_lib: ^0.2.2
  analyzer: ^4.0.0
  code_builder: any
  flutter_test:
    sdk: flutter
  path: any
  stream_transform: ^2.0.0

flutter:
  uses-material-design: true
