# Created with package:mono_repo v6.4.1
name: Build
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  job_001:
    name: "build_test; PKGS: packages/auth/amplify_auth_cognito_dart, packages/worker_bee/e2e; `dart test --tags=build`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@ac8075791e805656e71b4ba23325ace9e3421120
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/auth/amplify_auth_cognito_dart-packages/worker_bee/e2e;commands:test_3"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/auth/amplify_auth_cognito_dart-packages/worker_bee/e2e
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: stable
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - id: packages_auth_amplify_auth_cognito_dart_pub_upgrade
        name: packages/auth/amplify_auth_cognito_dart; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/auth/amplify_auth_cognito_dart
      - name: "packages/auth/amplify_auth_cognito_dart; dart test --tags=build"
        run: "dart test --tags=build"
        if: "always() && steps.packages_auth_amplify_auth_cognito_dart_pub_upgrade.conclusion == 'success'"
        working-directory: packages/auth/amplify_auth_cognito_dart
      - id: packages_worker_bee_e2e_pub_upgrade
        name: packages/worker_bee/e2e; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/worker_bee/e2e
      - name: "packages/worker_bee/e2e; dart test --tags=build"
        run: "dart test --tags=build"
        if: "always() && steps.packages_worker_bee_e2e_pub_upgrade.conclusion == 'success'"
        working-directory: packages/worker_bee/e2e
